compatibility_date = "2022-04-05"
main = "index.ts"
name = "demoskm-worker"
route = "api.demoskm.d1sql.com/*"
pages_build_output_dir = "./dist"
CLOUDFLARE_API_TOKEN = "e390069829d3a7c13440d50202ff414180bd2"

[[d1_databases]]
binding = "DB"
database_name = "workerskm1-db"
database_id = "30ea04cd-1511-4ac8-a8ba-da3ff58c0e49"

[observability]
enabled = true