compatibility_date = "2022-04-05"
main = "index.ts"
name = "demoskm-worker"
route = "api.demoskm.d1sql.com/*"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "b05ecb65-f065-4186-806e-cc1bf6913a0b"

[observability]
enabled = true
head_sampling_rate = 0.1