compatibility_date = "2022-04-05"
main = "index.ts"
name = "northwind-worker"
route = "api.northwind.d1sql.com/*"

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "d5b1d127-1d3f-467e-953b-cbc69f0a9e06"
